language: java

jdk:
  - oraclejdk8

sudo: false

addons:
  apt:
    packages:
      - protobuf-compiler

install: mvn install -DskipTests=true -Ptravis
script: mvn test -Ptravis

cache:
  directories:
    - $HOME/.m2

after_success:
  - mvn clean test jacoco:report coveralls:report