# Docker plugin configuration
packaging:
  add:
    - target/query-server.jar
    - target/query-trinity-${project.version}-plugin.zip
    - target/query-ontology-dsl-${project.version}-plugin.zip
    - target/aniketos-security-framework-provider-${aniketos.version}-plugin.zip
    - target/cache-ehcache-${df.cache.version}-plugin.zip
tag: quay.io/daedafusion/query